### ISSUE TITLE
Problem in running.

### ISSUE THREAD

**Issue by arpit-dwivedi** [amolikvivian/Social-Distance-Breach-Detector-OpenCV-DL#1]
It is giving this error:

`
Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
`

**Comment by amolikvivian** [comment]
@arpit-dwivedi Are you changing your directory to the correct location of the project?

**Comment by arpit-dwivedi** [comment]
@amolikvivian Yes I think so... Here is a screenshot of my terminal:
![Screenshot from 2020-07-01 07-21-18](https://user-images.githubusercontent.com/31418443/86194330-d94fc580-bb6b-11ea-84eb-acfea670bf88.png)

PS: I have not worked on  Flask before.

**Comment by arpit-dwivedi** [comment]
* For any one getting the same error, use `export` instead of `set` in linux terminal. Rename `Main.py` to `main.py` in command.
